package pkg;

public class Student {
/*a) Create a class called Student with the properties studentID(int), name(string), degree
(string), mobile(string)*/
    //variables
    private static int max = 100;
    private int studentID;

    private String name;
    private String degree;
    private String mobile;

    /*b) Create a constructor for the Student class to set values for name, degree and mobile
number. The student id should be generated by the system making use of a static
property called maxwhich is initialized to 100 initially to assign a unique value for each
student id.*/


    public Student(String name, String degree, String mobile)
    {
        this.studentID = max++;
        this.name = name;
        this.degree = degree;
        this.mobile = mobile;
    }

    /*c) Create setters and getters for name, degree and mobile.*/

    public void setName(String name) {
        this.name = name;
    }

    public void setDegree(String degree) {
        this.degree = degree;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getName() {
        return name;
    }

    public String getDegree(){
        return degree;
    }

    public String getMobile()
    {
        return mobile;
    }

    /*d) Create a print() method to print details of a student*/
    public void print()
    {
        System.out.println("Student Id : "+studentID);
        System.out.println("Name : "+name);
        System.out.println("Degree : "+degree);
        System.out.println("Mobile : "+mobile+"\n\n");
    }

    /*e) Create a static method called getNextStudentID() to return the next student id.*/
    public static int getNextStudentID() {
        return max;
    }


}
